//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZA_Membership.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZA_Membership.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect.
        /// </summary>
        internal static string CurrentPassword_Invalid {
            get {
                return ResourceManager.GetString("CurrentPassword_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        internal static string Email_AlreadyExists {
            get {
                return ResourceManager.GetString("Email_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        internal static string Jwt_InvalidToken {
            get {
                return ResourceManager.GetString("Jwt_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token has expired.
        /// </summary>
        internal static string Jwt_TokenExpired {
            get {
                return ResourceManager.GetString("Jwt_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        internal static string Jwt_Unauthorized {
            get {
                return ResourceManager.GetString("Jwt_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        internal static string Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string Login_Success {
            get {
                return ResourceManager.GetString("Login_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout failed.
        /// </summary>
        internal static string Logout_Failed {
            get {
                return ResourceManager.GetString("Logout_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout successful.
        /// </summary>
        internal static string Logout_Success {
            get {
                return ResourceManager.GetString("Logout_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged out from all devices.
        /// </summary>
        internal static string LogoutAllDevices_Success {
            get {
                return ResourceManager.GetString("LogoutAllDevices_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is invalid.
        /// </summary>
        internal static string NewPassword_Invalid {
            get {
                return ResourceManager.GetString("NewPassword_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        internal static string Password_Changed {
            get {
                return ResourceManager.GetString("Password_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string Password_Invalid {
            get {
                return ResourceManager.GetString("Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters long.
        /// </summary>
        internal static string Password_MinimumLength {
            get {
                return ResourceManager.GetString("Password_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number.
        /// </summary>
        internal static string Password_RequireDigit {
            get {
                return ResourceManager.GetString("Password_RequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter.
        /// </summary>
        internal static string Password_RequireLowercase {
            get {
                return ResourceManager.GetString("Password_RequireLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character.
        /// </summary>
        internal static string Password_RequireSpecialChar {
            get {
                return ResourceManager.GetString("Password_RequireSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter.
        /// </summary>
        internal static string Password_RequireUppercase {
            get {
                return ResourceManager.GetString("Password_RequireUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        internal static string Permission_Denied {
            get {
                return ResourceManager.GetString("Permission_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh token.
        /// </summary>
        internal static string RefreshToken_Failed {
            get {
                return ResourceManager.GetString("RefreshToken_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is not valid.
        /// </summary>
        internal static string RefreshToken_Invalid {
            get {
                return ResourceManager.GetString("RefreshToken_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is invalid or expired.
        /// </summary>
        internal static string RefreshToken_InvalidOrExpired {
            get {
                return ResourceManager.GetString("RefreshToken_InvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is required.
        /// </summary>
        internal static string RefreshToken_Required {
            get {
                return ResourceManager.GetString("RefreshToken_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token refreshed successfully.
        /// </summary>
        internal static string RefreshToken_Success {
            get {
                return ResourceManager.GetString("RefreshToken_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        internal static string Register_Failed {
            get {
                return ResourceManager.GetString("Register_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration completed successfully.
        /// </summary>
        internal static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        internal static string Register_UserExists {
            get {
                return ResourceManager.GetString("Register_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is already assigned to the user.
        /// </summary>
        internal static string Role_AlreadyAssigned {
            get {
                return ResourceManager.GetString("Role_AlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role assigned to user successfully.
        /// </summary>
        internal static string Role_Assigned {
            get {
                return ResourceManager.GetString("Role_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is not assigned to the user.
        /// </summary>
        internal static string Role_NotAssigned {
            get {
                return ResourceManager.GetString("Role_NotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found.
        /// </summary>
        internal static string Role_NotFound {
            get {
                return ResourceManager.GetString("Role_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role removed from user successfully.
        /// </summary>
        internal static string Role_Removed {
            get {
                return ResourceManager.GetString("Role_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A system error has occurred.
        /// </summary>
        internal static string System_Error {
            get {
                return ResourceManager.GetString("System_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully activated.
        /// </summary>
        internal static string User_Activated {
            get {
                return ResourceManager.GetString("User_Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deactivated.
        /// </summary>
        internal static string User_Deactivated {
            get {
                return ResourceManager.GetString("User_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is inactive.
        /// </summary>
        internal static string User_Inactive {
            get {
                return ResourceManager.GetString("User_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information updated successfully.
        /// </summary>
        internal static string User_InfoUpdated {
            get {
                return ResourceManager.GetString("User_InfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists.
        /// </summary>
        internal static string Username_AlreadyExists {
            get {
                return ResourceManager.GetString("Username_AlreadyExists", resourceCulture);
            }
        }
    }
}
